spring.application.name=kosa_1

#포트 설정 (webserver)
server.port=8090 


#DB작업  (기본 설정 : hikariDataSource 사용) **

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=springuser
spring.datasource.password=1004

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5         
spring.datasource.hikari.idle-timeout=30000     
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.max-lifetime=1800000   


#Mybatis  **
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=kr.or.kosa.model

# 한글처리
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true



# MyBatis Mapper XML 위치
#mybatis.mapper-locations=classpath:/mapper/*.xml

# DTO(VO) 패키지
#mybatis.type-aliases-package=com.example.demo.model

# Camel Case 자동 변환
#mybatis.configuration.map-underscore-to-camel-case=true
